name: Build Mac Installer

on:
  release:
    types: created 
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        brew install create-dmg

    - name: Build Installer
      run: |
        python -m pip install pyinstaller
        pyinstaller --windowed --add-data="_internal:_internal" Planner.py
        ./create-dmg.sh

    - name: Get Release ID
      id: get_release
      uses: actions/github-script@v6
      with:
        script: |
          const { data: releases } = await github.repos.listReleases({
            owner: context.repo.owner,
            repo: context.repo.repo
          });
          const release = releases.find(r => r.tag_name === '${{ github.ref_name }}');
          return release.id;
  
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: https://uploads.github.com/repos/${{ github.repository }}/releases/${{ steps.get_release.outputs.result }}/assets?name=installer.exe
        asset_path: dist/Planner.dmg
        asset_name: Mac Installer
        asset_content_type: application/octet-stream